version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    labels:
      - dependencies
      - github-actions
      - dependabot
